name: builds 
on: 
  push:
    tags:
      - '*'
      
jobs:
    build:
        runs-on: windows-latest
        steps:

        - name: login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASS }}
        
        - uses: actions/checkout@v4
        - name: builds and pushes the container
          shell: powershell
          run: ./build.ps1 --dockerpush true
